### ISSUE TITLE
Add table containing two columns; Shell Name and Shell URL!

### ISSUE THREAD

**Issue by TheBinitGhimire** [TheBinitGhimire/Web-Shells#4]
Hello there,

If you are reading this, here is an opportunity for you to create a valid PR in this repository!

You will just have to create a table in the **[README.md](../blob/master/README.md)** file, with two columns in it, one for the Shell Name, and the next one for the Shell URL.

For the Shell URL, use the text "Find Here!" for each row, and create a hyperlink for this text to the shell's filename in this repository.

The first person to do so would have his/her PR approved, merged as well as have the **hacktoberfest-accepted** label to his/her PR.

Thanks,
@TheBinitGhimire

**Comment by pr0d33p** [comment]
Hi @TheBinitGhimire,

I have done this and have opened the pull request.

Regards.
@pr0d33p

**Comment by TheBinitGhimire** [comment]
Hi @pr0d33p,

You were the first one to resolve this issue. Therefore, I have merged your PR to the original repository.

Thank you for contributing! 

Best of Luck for your further **Hacktoberfest 2020** journey!

Thanks,
@TheBinitGhimire
